# https://pre-commit.com/hooks.html
default_stages: [commit]
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-shebang-scripts-are-executable
      - id: check-docstring-first
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ["--fix"]
  - repo: https://github.com/crate-ci/typos
    rev: v1.17.0
    hooks:
      - id: typos
        files: |
          (?x)
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--preview, --quiet, --config, pyproject.toml]
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.0
    hooks:
      - id: isort
